Removed other files from compression

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -143,7 +143,7 @@ jobs:
         shell: bash
 
       - name: Configure Linux host
-        if: ${{ matrix.host == 'ubuntu-latest'}}
+        if: ${{ runner.os == 'Linux'}}
         run: |
           sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
           sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
@@ -154,12 +154,12 @@ jobs:
           echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
 
       - name: Configure Windows host
-        if: ${{ matrix.host == 'windows-latest'}}
+        if: ${{ runner.os == 'Windows'}}
         run: |
           choco install ccache -A
 
       - name: Configure macOS host
-        if: ${{ matrix.host == 'macos-latest'}}
+        if: ${{ runner.os == 'macOS'}}
         run: |
           brew install ccache ninja bash
           echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
@@ -223,33 +223,23 @@ jobs:
 
       - name: Build SuperGenius
         working-directory: ${{github.workspace}}/SuperGenius
-        run: cmake --build $BUILD_DIRECTORY --config ${{matrix.build-type}} -j
-        shell: bash
+        run: cmake --build ${{env.BUILD_DIRECTORY}} --config ${{matrix.build-type}} -j
 
       - name: Install SuperGenius
         working-directory: ${{github.workspace}}/SuperGenius/${{env.BUILD_DIRECTORY}}
         run: cmake --install .
 
-      - name: Compressing build Artifacts
-        working-directory: ${{github.workspace}}/SuperGenius
+      - name: Compress build artifacts
+        working-directory: ${{github.workspace}}/SuperGenius/${{env.BUILD_DIRECTORY}}
         if: ${{ github.event_name == 'workflow_dispatch' }}
         run: |
-          shopt -s extglob
-
-          IFS='/' read -ra dirs <<< "$BUILD_DIRECTORY"
-
-          for dir in "${dirs[@]}"; do
-            rm -rf !($dir) .[!.]* ..?*
-            cd $dir
-          done
-
-          cd $GITHUB_WORKSPACE
-          tar -czvf SuperGenius.tar.gz SuperGenius/
+          tar --exclude=.git -czvf SuperGenius.tar.gz --transform 's|^|${{env.BUILD_DIRECTORY}}|' SuperGenius/
         shell: bash
 
-      - name: Set release variables
-        id: vars
+      - name: Release file
         if: ${{ github.event_name == 'workflow_dispatch' }}
+        working-directory: ${{github.workspace}}/SuperGenius/${{env.BUILD_DIRECTORY}}
+        shell: bash
         run: |
           if [ '${{matrix.abi}}' ]; then
             OS_NAME=${{matrix.target}}-${{matrix.abi}}
@@ -261,32 +251,25 @@ jobs:
           build_type=Release
           file_name="${OS_NAME}-${branch_name}-${build_type}.tar.gz"
 
-          echo "RELEASE_TAG=${OS_NAME}-${branch_name}-${build_type}" >> $GITHUB_ENV
-          echo "RELEASE_NAME=${OS_NAME} ${branch_name} ${build_type}" >> $GITHUB_ENV
-          echo "FILE_NAME=$file_name" >> $GITHUB_ENV
+          RELEASE_TAG=${OS_NAME}-${branch_name}-${build_type}
 
-          mv SuperGenius.tar.gz $file_name
-        shell: bash
+          mv SuperGenius.tar.gz ${file_name}
 
-      - name: Create GitHub Release
-        if: ${{ github.event_name == 'workflow_dispatch' }}
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GNUS_TOKEN_1 }}
-        with:
-          tag_name: ${{ env.RELEASE_TAG }}
-          release_name: ${{ env.RELEASE_NAME }}
-          draft: false
-          prerelease: false
+          if ! gh release view $RELEASE_TAG; then
+              echo "Release not found, creating tag ${RELEASE_TAG}"
+              
+              if [ '${{ matrix.build-type }}' != 'Release' ]; then
+                  RELEASE_TYPE="--prerelease"
+              else
+                  RELEASE_TYPE="--latest"
+              fi
 
-      - name: Upload Release Asset
-        if: ${{ github.event_name == 'workflow_dispatch' }}
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GNUS_TOKEN_1 }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ env.FILE_NAME }}
-          asset_name: ${{ env.FILE_NAME }}
-          asset_content_type: application/gzip
+              gh release create ${RELEASE_TAG} \
+                  -n "${CURRENT_BRANCH} branch" \
+                  --target "${CURRENT_BRANCH}" \
+                  ${RELEASE_TYPE} \
+                  -t "${{ matrix.target }} ${{ matrix.abi && format('({0}) ', matrix.abi) || ''}}${CURRENT_BRANCH} branch ${{ matrix.build-type }} build"
+          fi
+
+          echo -e "Uploading ${file_name}"
+          gh release upload --clobber ${RELEASE_TAG} ${file_name}
