Fixed GitHub release

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -219,22 +219,24 @@ jobs:
         shell: bash
 
       - name: Release file
-        if: ${{ github.event_name == 'workflow_dispatch' }}
+        if: github.ref_name == 'main' || github.ref_name == 'develop'
         working-directory: ${{github.workspace}}/SuperGenius/${{env.BUILD_DIRECTORY}}
         shell: bash
         run: |
-          release_tag=${{matrix.target}}-${CURRENT_BRANCH}-${{matrix.build-type}}
+          RELEASE_TAG='${{matrix.target}}-${{github.ref_name}}-${{matrix.build-type}}'
 
-          if ! gh release view $release_tag; then
-              echo "Release not found, creating tag ${release_tag}"
-              
+          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
+
+          if ! gh release view $RELEASE_TAG; then
+              echo "Release not found, creating with tag: $RELEASE_TAG"
+
               if [ '${{ matrix.build-type }}' != 'Release' ]; then
                   RELEASE_TYPE="--prerelease"
               else
                   RELEASE_TYPE="--latest"
               fi
 
-              gh release create ${release_tag} \
+              gh release create $RELEASE_TAG \
                   -n "${CURRENT_BRANCH} branch" \
                   --target "${CURRENT_BRANCH}" \
                   ${RELEASE_TYPE} \
@@ -242,4 +244,4 @@ jobs:
           fi
 
           echo -e "Uploading ${FILE_NAME}"
-          gh release upload --clobber ${release_tag} ${FILE_NAME}
+          gh release upload --clobber ${RELEASE_TAG} ${FILE_NAME}
